# numpy tips

In [2]:
import numpy as np

# 配列を作る

In [3]:
print('要素を指定して配列を作る')
a = np.array([1,2,3,4,5])
print(f'np.array([1,2,3,4,5])\t=>\t{a}')
print()

print('順列で配列をつくる')
a = np.arange(5)
print(f'np.range(5)\t=>\t{a}')
print()

print('ゼロ埋めで配列をつくる')
a = np.zeros((5))
print(f'np.zeros((5))\t=>\t{a}')
a = np.zeros((5,5))
print(f'np.zeros((5,5))\t=>\n{a}')
print()

print('1埋めで配列をつくる')
a = np.ones((5))
print(f'np.ones((5))\t=>\t{a}')
a = np.ones((5,5))
print(f'np.ones((5,5))\t=>\n{a}')

print('ランダムな配列をつくる')

# ランダムな配列を作る
### まず、generatorの生成
gen= np.random.default_rng()
a = gen.random(3)
print(f'np.random.default_rng().random(3)\t=>\t{a}')

a = gen.integers(100)
print(f'np.random.default_rng().integers(100)\t=>\t{a}')

a = gen.integers(100,size=[10,2])
print(f'np.random.default_rng().integers(100,size=[10,2])\t=>\n{a}')


# sort　普通にsort関数/メソッドを使うと、すべての要素が指定された向きでソートされる
a = np.sort(a)
print(f'np.sort(a)\t=>\n{a}')
a = np.sort(a,axis=0)
print(f'np.sort(a,axis=0)\t=>\n{a}')
a = np.sort(a,axis=1)
print(f'np.sort(a,axis=1)\t=>\n{a}')



要素を指定して配列を作る
np.array([1,2,3,4,5])	=>	[1 2 3 4 5]

順列で配列をつくる
np.range(5)	=>	[0 1 2 3 4]

ゼロ埋めで配列をつくる
np.zeros((5))	=>	[0. 0. 0. 0. 0.]
np.zeros((5,5))	=>
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

1埋めで配列をつくる
np.ones((5))	=>	[1. 1. 1. 1. 1.]
np.ones((5,5))	=>
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
ランダムな配列をつくる
np.random.default_rng().random(3)	=>	[0.81744325 0.648652   0.79031534]
np.random.default_rng().integers(100)	=>	39
np.random.default_rng().integers(100,size=[10,2])	=>
[[75 57]
 [42 98]
 [14 43]
 [35 80]
 [32 24]
 [12 96]
 [52 62]
 [78  1]
 [78 32]
 [27 47]]
np.sort(a)	=>
[[57 75]
 [42 98]
 [14 43]
 [35 80]
 [24 32]
 [12 96]
 [52 62]
 [ 1 78]
 [32 78]
 [27 47]]
np.sort(a,axis=0)	=>
[[ 1 32]
 [12 43]
 [14 47]
 [24 62]
 [27 75]
 [32 78]
 [35 78]
 [42 80]
 [52 96]
 [57 98]]
np.sort(a,axis=1)	=>
[[ 1 32]
 [12 43]
 [14 47]
 [24 62]
 [27 75]
 [32 78]
 [35 78]
 [42 80]
 [52 96]
 [57 98]]


## ソート

### ソートはちょっと厄介。numpy.sortを使うと、いわゆるSQLのようにある列を基準にして行をソートする、というような動きはせず、指定された向きですべての要素をソートする

In [5]:
a = gen.integers(100,size=[5,2])
print(f'np.random.default_rng().integers(100,size=[10,2])\t=>\n{a}')


# sort　普通にsort関数/メソッドを使うと、すべての要素が指定された向きでソートされる
a = np.sort(a)
print(f'np.sort(a)\t=>\n{a}')
a1 = np.sort(a,axis=0)
print(f'np.sort(a,axis=0)\t=>\n{a1}')
a2 = np.sort(a,axis=1)
print(f'np.sort(a,axis=1)\t=>\n{a2}')

np.random.default_rng().integers(100,size=[10,2])	=>
[[35 85]
 [94 42]
 [45 80]
 [37 78]
 [31 86]]
np.sort(a)	=>
[[35 85]
 [42 94]
 [45 80]
 [37 78]
 [31 86]]
np.sort(a,axis=0)	=>
[[31 78]
 [35 80]
 [37 85]
 [42 86]
 [45 94]]
np.sort(a,axis=1)	=>
[[35 85]
 [42 94]
 [45 80]
 [37 78]
 [31 86]]


### いわゆる、テーブルデータで期待するソートは以下のように実施する

* これって、配列が巨大だった場合、巨大な配列の並び替えたコピーを作るってことで、データが巨大な場合は注意が必要。
* ソート順の配列を取得する際のソートのアルゴリズムは選択できるらしいけど、そのインデックスをもとに巨大な配列を作り直すということになるので

In [6]:
print(f'a =>\n{a}\n')
sorted_index = np.argsort(a,axis=0)
print(f'np.argsort(a,axis=0) =\n{sorted_index}\n')
print(f'sorted_index[:,0] =\n{sorted_index[:,0]}\n')
a3 = a[sorted_index[:,0]]
print(f'a[sorted_index[:,0]]\t=>\n{a3}\n')

a =>
[[35 85]
 [42 94]
 [45 80]
 [37 78]
 [31 86]]

np.argsort(a,axis=0) =
[[4 3]
 [0 2]
 [3 0]
 [1 4]
 [2 1]]

sorted_index[:,0] =
[4 0 3 1 2]

a[sorted_index[:,0]]	=>
[[31 86]
 [35 85]
 [37 78]
 [42 94]
 [45 80]]



## numpayの配列の演算

### ndarrayの四則演算は、同じ大きさの配列の場合、同じインデックスの要素ごとに四則演算をしてくれる

詳しくはここを参照。https://note.nkmk.me/python-numpy-matrix/

In [8]:
# numpyのarrayの四則演算

# 1列の場合
a = np.array((3,6,16))
b = np.array((1,2,4))
print(f'a + b = {a + b}')
print(f'a - b = {a - b}')
print(f'a * b = {a * b}')
print(f'a / b = {a / b}')

# 2列の場合
a = np.array([[3,6,16],[6,12,32]])
b = np.array([[1,2,4],[2,4,8]])

print(f'a + b = {a + b}')
print(f'a - b = {a - b}')
print(f'a * b = {a * b}')
print(f'a / b = {a / b}')

# @
print(f'a @ b.T = {a @ b.T}')
print(f'a.T @ b = {a.T @ b}')    

a + b = [ 4  8 20]
a - b = [ 2  4 12]
a * b = [ 3 12 64]
a / b = [3. 3. 4.]
a + b = [[ 4  8 20]
 [ 8 16 40]]
a - b = [[ 2  4 12]
 [ 4  8 24]]
a * b = [[  3  12  64]
 [ 12  48 256]]
a / b = [[3. 3. 4.]
 [3. 3. 4.]]
a @ b.T = [[ 79 158]
 [158 316]]
a.T @ b = [[ 15  30  60]
 [ 30  60 120]
 [ 80 160 320]]


## numpy ndarrayを条件でフィルタリングする

### 単純な条件判断

評価オペランドで、その評価結果の配列が返却される

In [11]:
a = gen.integers(100,size=[10])

print(f'a\t{a}')
print(f'a>50\t{a>50}')

a = gen.integers(5,size=[10])
print(f'a\t{a}')
print(f'a==0\t{a==0}')

a	[60 54 38 82 82 13 37 65 62 29]
a>50	[ True  True False  True  True False False  True  True False]
a	[4 1 0 0 4 0 0 4 2 1]
a==0	[False False  True  True False  True  True False False False]


### 条件に合致したものを取り出す式

In [13]:
print('1次元の場合')
a = gen.integers(5,size=[10])
print(f'a\t{a}')
print(f'a<3\t{a<3}')
print(f'a[a<3]\t{a[a<3]}')

print('2次元の場合')
a = gen.integers(5,size=[10,2])
print(f'a\n{a}')
print(f'a<3\n{a<3}')
print('1列目が3より小さいのものを抽出')
print(f'(a<3)[:,0]\n{(a<3)[:,0]}')
print(f'a[(a<3)[:,0]]\n{a[(a<3)[:,0]]}')


1次元の場合
a	[0 2 3 0 4 3 0 3 4 1]
a<3	[ True  True False  True False False  True False False  True]
a[a<3]	[0 2 0 0 1]
2次元の場合
a
[[2 3]
 [3 3]
 [0 2]
 [1 4]
 [1 0]
 [1 2]
 [0 4]
 [4 0]
 [2 0]
 [0 0]]
a<3
[[ True False]
 [False False]
 [ True  True]
 [ True False]
 [ True  True]
 [ True  True]
 [ True False]
 [False  True]
 [ True  True]
 [ True  True]]
1列目が3より小さいのものを抽出
(a<3)[:,0]
[ True False  True  True  True  True  True False  True  True]
a[(a<3)[:,0]]
[[2 3]
 [0 2]
 [1 4]
 [1 0]
 [1 2]
 [0 4]
 [2 0]
 [0 0]]


In [15]:
### 応用

yt = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
yp = np.array([0, 1, 1, 0, 1, 0, 0, 0, 1, 0])

print("ypが0に対応するytを抽出する")
print(f'yt\t{yt}')
print(f'yp\t{yp}')
print(f'yp==0\t{yp==0}')
print(f'yt[yp==0]\t{yt[yp==0]}')
print()

print('ytの値が4より大きいものに対応するypを抽出する')
print(f'yt\t{yt}')
print(f'yp\t{yp}')
print(f'yt>4\t{yt>4}')
print(f'yp[yt>4]\t{yp[yt>4]}')

ypが0に対応するytを抽出する
yt	[0 1 2 3 4 5 6 7 8 9]
yp	[0 1 1 0 1 0 0 0 1 0]
yp==0	[ True False False  True False  True  True  True False  True]
yt[yp==0]	[0 3 5 6 7 9]

ytの値が4より大きいものに対応するypを抽出する
yt	[0 1 2 3 4 5 6 7 8 9]
yp	[0 1 1 0 1 0 0 0 1 0]
yt>4	[False False False False False  True  True  True  True  True]
yp[yt>4]	[0 0 0 1 0]


# dictinct関連

In [4]:
yp = np.array([0, 1, 2, 0, 1, 2, 0, 0, 1, 0, 1, 2, 1, 2, 1, 0, 1, 0, 2, 0])

# 重複を排除した値を取得
print(f'distinct(*):重複を排除した値を取得')
print(f'np.unique(yp) => {np.unique(yp)}\n')

print(f'distinct(count(*)):重複を排除した値の行数を取得=>種類数を取得')
print(f'np.unique(yp).size => {np.unique(yp).size}\n')

print(f'重複した項目の出現回数を取得する     => 要素のndarray、対応する出現回数のndarrayのタプル')
print(f'np.unique(yp, return_counts=True) => {np.unique(yp, return_counts=True)}\n')


distinct(*):重複を排除した値を取得
np.unique(yp) => [0 1 2]

distinct(count(*)):重複を排除した値の行数を取得=>種類数を取得
np.unique(yp).size => 3

重複した項目の出現回数を取得する     => 要素のndarray、対応する出現回数のndarrayのタプル
np.unique(yp, return_counts=True) => (array([0, 1, 2]), array([8, 7, 5]))



# 最大値/最小値、最大値の要素インデックス/最小値の要素インデックスの取得

* 最大値/最小値の取得 np.max/min
* 最大値の要素インデックス/最小値の要素インデックスの取得　np.argmax/argmin

In [24]:
a = np.random.default_rng().integers(30,size=[10,3])
#a = np.(30).reshape((10,3))
print(f'a => \n{a}\n')

# max/minの場合
print('np.maxの結果')
print(f'  np.max(a) => {np.max(a)}')
print(f'  np.max(a,axis=0) => {np.max(a,axis=0)}')
print(f'  np.max(a,axis=1) => {np.max(a,axis=1)}')
print('np.minの結果')
print(f'  np.min(a) => {np.min(a)}')
print(f'  np.min(a,axis=0) => {np.min(a,axis=0)}')
print(f'  np.min(a,axis=1) => {np.min(a,axis=1)}')
print()

# axisを設定しない場合、単純にmax値が返却
print('np.argmaxの結果')
print(f'  np.argmax(a) => {np.argmax(a)}')
print(f'  np.argmax(a,axis=0) => {np.argmax(a,axis=0)}')
print(f'  np.argmax(a,axis=1) => {np.argmax(a,axis=1)}')
print('np.argminの結果')
print(f'  np.argmin(a) => {np.argmax(a)}')
print(f'  np.argmin(a,axis=0) => {np.argmin(a,axis=0)}')
print(f'  np.argmin(a,axis=1) => {np.argmin(a,axis=1)}')



a => 
[[16 27 26]
 [14 12 29]
 [19 16 15]
 [15 20 10]
 [11 19 18]
 [ 4 23 23]
 [22 25 17]
 [29 18 24]
 [ 6  7 29]
 [ 8  9  6]]

np.maxの結果
  np.max(a) => 29
  np.max(a,axis=0) => [29 27 29]
  np.max(a,axis=1) => [27 29 19 20 19 23 25 29 29  9]
np.minの結果
  np.min(a) => 4
  np.min(a,axis=0) => [4 7 6]
  np.min(a,axis=1) => [16 12 15 10 11  4 17 18  6  6]

np.argmaxの結果
  np.argmax(a) => 5
  np.argmax(a,axis=0) => [7 0 1]
  np.argmax(a,axis=1) => [1 2 0 1 1 1 1 0 2 1]
np.argminの結果
  np.argmin(a) => 5
  np.argmin(a,axis=0) => [5 8 9]
  np.argmin(a,axis=1) => [0 1 2 2 0 0 2 1 0 2]


# 配列の結合

In [22]:
a = np.arange(10)
b = np.arange(10,20)

# テスト対象データ
print(a)
print(b)


[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


## 横方向（カラム方向）に結合

### １次元配列の場合は、１列の行列に変換し、横に結合

In [49]:
print('引数に一つの配列を渡すと、１列の行列を返却')
print(f'np.c_[a] => \n{np.c_[a]}\n')

print('引数に２つの配列を渡すと、それぞれ１列の行列に変換し、横に結合')
print(f'np.c_[a,b] =>\n{np.c_[a,b]}')

引数に一つの配列を渡すと、１列の行列を返却
np.c_[a] => 
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

引数に２つの配列を渡すと、それぞれ１列の行列に変換し、横に結合
np.c_[a,b] =>
[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]


### 元が行列の場合、単純に横に結合

In [45]:
ar = a.reshape([5,2])
br = b.reshape([5,2])

print(f'a.reshape([5,2]) =>\n{ar}')
print(f'b.reshape([5,2]) =>\n{br}\n')

arbr = np.c_[ar,br]
print(f'np.c_[ar,br] =>\n{arbr}\n')

print('列数は一致していなくてOK')

arbrar = np.c_[arbr,ar]

print(f'np.c_[arbr,ar] => \n{arbrar}')

print('結合軸（行数）が一致していないとエラー')
print('np.c_[a,ar]')
np.c_[a,ar]


a.reshape([5,2]) =>
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
b.reshape([5,2]) =>
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

np.c_[ar,br] =>
[[ 0  1 10 11]
 [ 2  3 12 13]
 [ 4  5 14 15]
 [ 6  7 16 17]
 [ 8  9 18 19]]

列数は一致していなくてOK
np.c_[arbr,ar] => 
[[ 0  1 10 11  0  1]
 [ 2  3 12 13  2  3]
 [ 4  5 14 15  4  5]
 [ 6  7 16 17  6  7]
 [ 8  9 18 19  8  9]]
結合軸（行数）が一致していないとエラー
np.c_[a,ar]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 10 and the array at index 1 has size 5

### c_関数を使った配列の縦ベクトル化

In [57]:
print(f'a =>\n{a}\n')
print(f'a.reshape([10,1]) =>\n{a.reshape([10,1])}\n')
print(f'np.c_[a] =>{np.c_[a]}\n')

print(f'a.reshape([10,1]) == np.c_[a] =>{a.reshape([10,1]) == np.c_[a]}')

a =>
[0 1 2 3 4 5 6 7 8 9]

a.reshape([10,1]) =>
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

np.c_[a] =>[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

a.reshape([10,1]) == np.c_[a] =>[[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]]


## 縦方向（行方向）に結合

１次元配列の場合、そのまま後ろに結合される

In [62]:
print(f'a => {a}')
print(f'b => {b}\n')
print(f'np.r_[a,b] =>\n{np.r_[a,b]}\n')
print()


print(f'ar => {ar}')
print(f'br => {br}\n')
print(f'np.r_[ar,br] =>\n{np.r_[ar,br]}')



a => [0 1 2 3 4 5 6 7 8 9]
b => [10 11 12 13 14 15 16 17 18 19]

np.r_[a,b] =>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


ar => [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
br => [[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

np.r_[ar,br] =>
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


# numpy.save／load

In [25]:
x1 = np.arange(8)
x2 = np.arange(8,16)
x11 = x1.reshape((2,2,2))
x21 = x2.reshape((2,2,2))

rr = np.r_[x11,x21]

print(f'x11:{x11}')
print(f'x21:{x21}')
print(f'rr:{rr}')


x11:[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
x21:[[[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
rr:[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


### numpy.saveは、ndarrayじゃなくても、array like objectであればシリアライズできるみたい

In [28]:
results = []
results.append(x11)
results.append(x21)

results

np.save('tmp/np_save',results)

In [29]:
results

[array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11]],
 
        [[12, 13],
         [14, 15]]])]

### loadすると、もともとPythonのlistだったものが、ndarrayに変換されて保存されていることがわかる。

In [31]:
loaded = np.load('tmp/np_save.npy')

In [36]:
loaded

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [37]:
loaded = np.load('images/PXL_20240121_053909046.TS.mp4.pred.mp4.npy')

In [39]:
loaded.shape

(194, 1, 1, 17, 3)

In [40]:
del loaded

In [42]:
import gc

gc.collect()

2223